version: '2'
services:
  base:
    extends:
      file: common.yml
      service: common
    build: ../base/
    image: victorock/scaleio2:base
    environment:
      - "affinity:container!=~base*"
    volumes:
      - /opt/emc/scaleio/sds
      - /opt/emc/scaleio/sds1
      - /opt/emc/scaleio/sds2
      - /opt/emc/scaleio/sds3
      - /opt/emc/scaleio/sds4
      - /opt/emc/scaleio/mdm
      - /opt/emc/scaleio/gateway
      - /etc/puppet:/etc/puppet
