version: '2'
services:
  BASE:
    privileged: true
    restart: always
    network_mode: host
    env_file: config.env
    build: ../base/
    image: victorock/scaleio2:base
    container_name: BASE

  LIA:
    privileged: true
    restart: always
    network_mode: host
    env_file: config.env
    build: ../lia/
    image: victorock/scaleio2:lia
    container_name: LIA
    ports:
      - "9099:9099"
    depends_on:
      - BASE
    volumes_from:
      - BASE
    volumes:
      - /dev/shm:/dev/shm

  GW:
    privileged: true
    restart: always
    network_mode: host
    env_file: config.env
    build: ../gateway/
    image: victorock/scaleio2:gateway
    container_name: GW
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - BASE
    volumes_from:
      - BASE
    volumes:
      - /dev/shm:/dev/shm

  TB:
    privileged: true
    restart: always
    network_mode: host
    env_file: config.env
    build: ../tb/
    image: victorock/scaleio2:tb
    container_name: TB
    environment:
      MDM_ROLE_IS_MANAGER: "0"
    ports:
      - "6611:6611"
      - "9011:9011"
      - "25600:25600"
    depends_on:
      - BASE
    volumes_from:
      - BASE
    volumes:
      - /dev/shm:/dev/shm
