version: '2.0'
services:
  SIO-BASE:
    extends:
      file: base.yml
      service: sio-base
    container_name: SIO-BASE

  SIO-GW:
    extends:
      file: base.yml
      service: sio-base
    container_name: SIO-GW
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - SIO-BASE
    volumes_from:
      - SIO-BASE
    volumes:
      - /dev/shm:/dev/shm

  SIO-MDM:
    privileged: true
    restart: always
    network_mode: host
    env_file: config.env
    build: ../sio-mdm/
    image: victorock/scaleio2:mdm
    container_name: SIO-MDM
    ports:
      - "6611:6611"
      - "9011:9011"
      - "25620:25620"
    depends_on:
      - SIO-BASE
    volumes_from:
      - SIO-BASE
    volumes:
      - /dev/shm:/dev/shm
