version: '2'
services:
  SIO-BASE:
    restart: always
    build: ../sio-base/
    image: victorock/scaleio2:base
    container_name: SIO-BASE

  SIO-GW:
    privileged: true
    restart: always
    network_mode: host
    env_file: config.env
    build: ../sio-gateway/
    image: victorock/scaleio2:gateway
    container_name: SIO-GW
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - SIO-BASE
    volumes_from:
      - SIO-BASE
    volumes:
      - /dev/shm:/dev/shm

  SIO-MDM:
    privileged: true
    restart: always
    network_mode: host
    env_file: config.env
    build: ../sio-mdm/
    image: victorock/scaleio2:mdm
    container_name: SIO-MDM
    environment:
      MDM_ROLE_IS_MANAGER: "0"
    ports:
      - "6611:6611"
      - "9011:9011"
      - "25600:25600"
    depends_on:
      - SIO-BASE
    volumes_from:
      - SIO-BASE
    volumes:
      - /dev/shm:/dev/shm
