version: '2'
services:
  lia:
    extends:
      file: common.yml
      service: common
    build: ../lia/
    image: victorock/scaleio2:lia
    environment:
      - "affinity:container!=~lia*"
    ports:
      - "9099:9099"
    depends_on:
      - base
    volumes_from:
      - base
