version: '2'
services:
  mdm:
    extends:
      file: common.yml
      service: common
    build: ../mdm/
    image: victorock/scaleio2:mdm
    environment:
      - "affinity:container!=~tb*"
      - "affinity:container!=~mdm*"
    ports:
      - "6611:6611"
      - "9011:9011"
      - "25620:25620"
    depends_on:
      - base
      - lia
    volumes_from:
      - base
    volumes:
      - /dev/shm:/dev/shm
