version: '2'
services:
  sds:
    extends:
      file: common.yml
      service: common
    build: ../sds/
    image: victorock/scaleio2:sds
    environment:
      - "affinity:container!=~sds*"
    ports:
      - "7072:7072"
      - "25640:25640"
    depends_on:
      - base
    volumes_from:
      - base
    volumes:
      - /dev/shm:/dev/shm
