version: '2'
services:
  sds1:
    extends:
      file: common.yml
      service: common
    build: ../sds1/
    image: victorock/scaleio2:sds1
    environment:
      - "affinity:container!=~sds1*"
      - INSTANCE=1
    ports:
      - "7073:7073"
      - "25641:25641"
    depends_on:
      - base
    volumes_from:
      - base
    volumes:
      - /dev/shm:/dev/shm
