version: '2'
services:
  sio-sds1:
    extends:
      file: base.yml
      service: sio-base
    build: ../sio-sds/
    image: victorock/scaleio2:sds
    environment:
      - "affinity:container!=~sio-sds2*"
      - INSTANCE=2
    ports:
      - "7074:7074"
      - "25642:25642"
    depends_on:
      - sio-base
    volumes_from:
      - sio-base
    volumes:
      - /dev/shm:/dev/shm
