version: '2'
services:
  sds2:
    extends:
      file: common.yml
      service: common
    build: ../sds2/
    image: victorock/scaleio2:sds2
    environment:
      - "affinity:container!=~sds2*"
      - INSTANCE=2
    ports:
      - "7074:7074"
      - "25642:25642"
    depends_on:
      - base
    volumes_from:
      - base
    volumes:
      - /dev/shm:/dev/shm
