version: '2'
services:
  SIO-BASE:
    restart: always
    build: ../sio-base/
    image: victorock/scaleio2:base
    container_name: SIO-BASE

  SIO-SDS3:
    privileged: true
    restart: always
    network_mode: host
    env_file: config.env
    build: ../sio-sds/
    image: victorock/scaleio2:sds
    container_name: SIO-SDS3
    environment:
      INSTANCE: 3
    ports:
      - "7075:7075"
      - "25643:25643"
    depends_on:
      - SIO-BASE
    volumes_from:
      - SIO-BASE
    volumes:
      - /dev/shm
