version: '2'
services:
  sio-sds3:
    extends:
      file: base.yml
      service: sio-base
    build: ../sio-sds/
    image: victorock/scaleio2:sds
    environment:
      - "affinity:container!=~sio-sds3*"
      - INSTANCE=3
    ports:
      - "7075:7075"
      - "25643:25643"
    depends_on:
      - sio-base
    volumes_from:
      - sio-base
    volumes:
      - /dev/shm:/dev/shm
