version: '2'
services:
  sds3:
    extends:
      file: common.yml
      service: common
    build: ../sds3/
    image: victorock/scaleio2:sds3
    environment:
      - "affinity:container!=~sds3*"
      - INSTANCE=3
    ports:
      - "7075:7075"
      - "25643:25643"
    depends_on:
      - base
    volumes_from:
      - base
    volumes:
      - /dev/shm:/dev/shm
