version: '2'
services:
  sio-sds4:
    extends:
      file: base.yml
      service: sio-base
    build: ../sio-sds/
    image: victorock/scaleio2:sds
    environment:
      - "affinity:container!=~sio-sds4*"
      - INSTANCE=4
    ports:
      - "7076:7076"
      - "25644:25644"
    depends_on:
      - sio-base
    volumes_from:
      - sio-base
    volumes:
      - /dev/shm:/dev/shm
