version: '2'
services:
  sds4:
    extends:
      file: common.yml
      service: common
    build: ../sds4/
    image: victorock/scaleio2:sds4
    environment:
      - "affinity:container!=~sds4*"
      - INSTANCE=4
    ports:
      - "7076:7076"
      - "25644:25644"
    depends_on:
      - base
    volumes_from:
      - base
    volumes:
      - /dev/shm:/dev/shm
