version: '2'
services:
  tb:
    extends:
      file: common.yml
      service: common
    build: ../tb/
    image: victorock/scaleio2:tb
    environment:
      - MDM_ROLE_IS_MANAGER=0
      - "affinity:container!=~tb*"
      - "affinity:container!=~mdm*"
    ports:
      - "6611:6611"
      - "9011:9011"
      - "25600:25600"
    depends_on:
      - base
      - lia
    volumes_from:
      - base
    volumes:
      - /dev/shm:/dev/shm
